export const COLORS = {
  bg: '#0A0B10',
  surface: '#12141C',
  border: '#1E2230',
  text: {
    primary: '#F0F2F5',
    secondary: '#8E9299',
    muted: '#4D535E',
  },
  accent: {
    green: '#10B981',
    red: '#EF4444',
    blue: '#3B82F6',
    purple: '#8B5CF6',
  },
};

export const MOCK_POSITIONS = [
  { 
    id: 'tr-1',
    ticker: 'BAJFINANCE.NS', 
    side: 'BUY', 
    qty: 50, 
    entryPrice: 7120.40, 
    currentPrice: 7145.20, 
    pnl: 1240.00, 
    confidence: 94, 
    algoName: 'Momentum_v2',
    target_price: 7340.00,
    stop_price: 7040.00,
    rr: 2.9,
    break_even: 7135.00,
    entry_time: '2024-05-03 10:15',
    reason_for_entry: 'VCP Breakout following strong institutional delivery.',
    ai_status: 'APPROVED',
    news_context: ['Sector tailwinds in NBFC', 'Positive Q3 guidance'],
    detailed_reasoning: 'Validation confirmed via positive sentiment in Q3 earnings sentiment and sector rotation into NBFCs. Past error on 2023-11-12 (INFY) flagged: avoided similar gap-up over-extension.',
    setup_status: 'APPROVED',
    setup_signal_type: 'Pivot Breakout',
    trade_exited: false,
    aiAccuracy: 'HIGH',
    keyMistake: 'None',
    humanCorrection: 'Perfect execution on this setup.',
    aiImprovement: 'Consider checking multi-timeframe RS.',
    lessonLearnt: 'VCP breakouts are reliable with institutional dryup.',
    goldenLesson: 'The 3rd contraction is usually the launchpad.',
    humanInstruction: 'Watch for the volume pocket.'
  },
  { 
    id: 'tr-2',
    ticker: 'RELIANCE.NS', 
    side: 'BUY', 
    qty: 100, 
    entryPrice: 2840.00, 
    currentPrice: 2838.10, 
    pnl: -190.00, 
    confidence: 82, 
    algoName: 'Screener_Alpha',
    target_price: 3000.00,
    stop_price: 2780.00,
    rr: 2.5,
    break_even: 2860.00,
    entry_time: '2024-05-02 11:30',
    reason_for_entry: 'Daily consolidation near 52W high.',
    ai_status: 'APPROVED',
    news_context: ['Crude prices stabilizing'],
    detailed_reasoning: 'Price action showing high tightness. Volume dry up noted.',
    setup_status: 'APPROVED',
    setup_signal_type: 'Trend Continuity',
    trade_exited: false,
    aiAccuracy: 'MEDIUM',
    keyMistake: 'Late entry relative to local pivot',
    humanCorrection: 'Entry should have been closer to 2820.',
    aiImprovement: 'Improve stop loss placement logic.',
    lessonLearnt: 'Trend continuity setups require strong index support.',
    goldenLesson: 'Index support is a multiplier for success.',
    humanInstruction: 'Scale in slowly on trend continuation.'
  },
  { 
    id: 'tr-3',
    ticker: 'TATASTEEL.NS', 
    side: 'BUY', 
    qty: 1200, 
    entryPrice: 142.15, 
    currentPrice: 145.40, 
    pnl: 3900.00, 
    confidence: 78, 
    algoName: 'Minervini_S1',
    target_price: 160.00,
    stop_price: 138.00,
    rr: 3.2,
    break_even: 144.00,
    entry_time: '2024-05-01 09:45',
    reason_for_entry: 'Stage 2 uptrend with RS > 85.',
    ai_status: 'APPROVED',
    news_context: ['Steel demand rising', 'Infrastructure Push'],
    detailed_reasoning: 'Strong weekly relative strength. Moving average alignment perfect.',
    setup_status: 'APPROVED',
    setup_signal_type: 'Stage 2 Continuation',
    trade_exited: false
  },
];

export const MOCK_TRADES = [
  ...MOCK_POSITIONS,
  { 
    id: 'tr-4',
    ticker: 'INFY.NS', 
    side: 'BUY', 
    qty: 100, 
    entryPrice: 1650.00, 
    currentPrice: 1720.00, 
    pnl: 7000.00, 
    confidence: 88, 
    algoName: 'Momentum_v2',
    target_price: 1750.00,
    stop_price: 1620.00,
    rr: 3.3,
    break_even: 1670.00,
    entry_time: '2024-04-20 10:00',
    exit_time: '2024-04-25 15:15',
    exit_price: 1720.00,
    reason_for_entry: 'IT Sector rebound after US inflation data.',
    ai_status: 'APPROVED',
    news_context: ['Nasdaq rally', 'Accenture guidance upgrade'],
    detailed_reasoning: 'Strong price persistence. Low drag on pullbacks.',
    setup_status: 'APPROVED',
    setup_signal_type: 'Pullback Entry',
    trade_exited: true,
    aiAccuracy: 'HIGH',
    keyMistake: 'None',
    humanCorrection: 'Perfect entry alignment.',
    aiImprovement: 'None needed',
    lessonLearnt: 'Breakouts from high-tightness consolidations are high-probability.',
    goldenLesson: 'Look for VCP tightness before breakouts.',
    humanInstruction: 'None'
  },
  { 
    id: 'tr-5',
    ticker: 'HDFCBANK.NS', 
    side: 'BUY', 
    qty: 200, 
    entryPrice: 1450.00, 
    currentPrice: 1420.00, 
    pnl: -6000.00, 
    confidence: 91, 
    algoName: 'Screener_Alpha',
    target_price: 1550.00,
    stop_price: 1420.00,
    rr: 3.3,
    break_even: 1470.00,
    entry_time: '2024-04-15 11:30',
    exit_time: '2024-04-18 14:00',
    exit_price: 1420.00,
    reason_for_entry: 'Support bounce at major psychological level.',
    ai_status: 'REJECTED',
    news_context: ['Private bank sector underperforming'],
    detailed_reasoning: 'AI expected liquidity sweep. Sweep occurred but follow through failed.',
    setup_status: 'REJECTED',
    setup_signal_type: 'Support Bounce',
    trade_exited: true,
    keyMistake: 'Ignored overall bank sector weakness during broad market correction.',
    humanCorrection: 'AI should cross-reference sector relative strength before counter-trend support entries.',
    aiImprovement: 'Add a rule to filter out support bounces if the sector is in a stage-4 decline.',
    lessonLearnt: 'Sector weakness can overpower individual stock support levels.',
    aiAccuracy: 'MEDIUM',
    goldenLesson: 'Check sector correlation before counter-trend entries.',
    humanInstruction: 'Cross-reference sector RS.'
  }
];

export const MOCK_ACTIVITY = [
  { id: 1, type: 'SCREENER', message: 'Screener added 5 stocks to watchlist', time: '10:15 AM' },
  { id: 2, type: 'VALIDATOR', message: 'REJECTED setup on CIPLA: High relative volume but news is negative', time: '10:30 AM' },
  { id: 3, type: 'EVALUATOR', message: 'New lesson learned for INFY: "Avoid breakouts near psychological levels"', time: '11:15 AM' },
  { id: 4, type: 'TRADE', message: 'Executed BUY order for RELIANCE at 2450.50', time: '11:45 AM' },
];

export const TECHNICAL_SIGNALS = [
  'EMA Crossover',
  'MACD Cross',
  'RSI Extremes',
  'Bollinger Band Squeeze',
  'Volume Profile Break',
  'VCP Tightness',
  'Pivot Breakout',
  'Moving Average Crossover',
  'RSI Divergence',
  'Gap Up Momentum',
  'Support/Resistance Bounce',
  'Create New...'
];

export const AVAILABLE_STOCKS = [
  'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'INFY.NS', 'ICICIBANK.NS', 
  'HINDUNILVR.NS', 'SBI.NS', 'BHARTIARTL.NS', 'BAJFINANCE.NS', 'LICI.NS',
  'ITC.NS', 'ADANIENT.NS', 'KOTAKBANK.NS', 'LT.NS', 'TITAN.NS'
];
